SELECT "OFFENSE_DESCRIPTION", COUNT(*)
FROM boscrime
GROUP BY "OFFENSE_DESCRIPTION"
ORDER BY COUNT(*) DESC;

SELECT DISTINCT "OFFENSE_DESCRIPTION"
FROM boscrime;

SELECT "OFFENSE_CODE", "OFFENSE_DESCRIPTION", "SHOOTING" 
FROM boscrime;

SELECT DISTINCT "OFFENSE_DESCRIPTION","SHOOTING" 
FROM boscrime
WHERE "SHOOTING"='1';