mkdir $HOME/DSJungle
mkdir $HOME/DSJungle/data
mkdir $HOME/DSJungle/python
mkdir $HOME/DSJungle/python/samples
mkdir $HOME/DSJungle/python/samples/sklearn
mkdir $HOME/DSJungle/python/samples/sklearn/nb
mkdir $HOME/DSJungle/python/samples/sklearn/py
mkdir $HOME/DSJungle/python/samples/tensorflow
mkdir $HOME/DSJungle/scripts
mkdir $HOME/DSJungle/sql
